import type { LevelConfig, ScenarioKind } from "./types";

const BEGINNER_POOL: ScenarioKind[] = ["single_die", "coin_flips"];
const INTERMEDIATE_POOL: ScenarioKind[] = ["single_die", "two_dice", "coin_flips"];
const ADVANCED_POOL: ScenarioKind[] = ["two_dice", "die_plus_fixed", "coin_flips", "card_draw"];
const HARD_POOL: ScenarioKind[] = [
  "die_plus_fixed",
  "two_dice",
  "coin_flips",
  "card_draw",
  "cards_with_reveal",
];

export const LEVELS: LevelConfig[] = [
  {
    id: "beginner",
    name: "Beginner",
    tier: "standard",
    description: "Wide spreads, simple dice and coin scenarios, generous timer.",
    fairTolerance: 1.0,
    minSpread: 0.5,
    maxSpread: 6,
    roundSeconds: 45,
    roundsToClear: 4,
    pnlTarget: 0,
    aiAggression: 0.5,
    aiEdgeThreshold: 0.75,
    scenarioPool: BEGINNER_POOL,
    inventorySkew: 0,
  },
  {
    id: "intermediate",
    name: "Intermediate",
    tier: "standard",
    description: "Two-dice sums and tighter fair-value tolerance.",
    fairTolerance: 0.75,
    minSpread: 0.75,
    maxSpread: 4,
    roundSeconds: 35,
    roundsToClear: 5,
    pnlTarget: 1,
    aiAggression: 0.6,
    aiEdgeThreshold: 0.5,
    scenarioPool: INTERMEDIATE_POOL,
    inventorySkew: 0.1,
  },
  {
    id: "advanced",
    name: "Advanced",
    tier: "standard",
    description: "Partial information, card markets, inventory skew matters.",
    fairTolerance: 0.5,
    minSpread: 1,
    maxSpread: 3.5,
    roundSeconds: 30,
    roundsToClear: 5,
    pnlTarget: 2,
    aiAggression: 0.7,
    aiEdgeThreshold: 0.35,
    scenarioPool: ADVANCED_POOL,
    inventorySkew: 0.2,
  },
  {
    id: "hard",
    name: "Hard",
    tier: "standard",
    description: "Multi-card reveals, tight spreads, fast clock.",
    fairTolerance: 0.35,
    minSpread: 1,
    maxSpread: 2.5,
    roundSeconds: 25,
    roundsToClear: 6,
    pnlTarget: 3,
    aiAggression: 0.75,
    aiEdgeThreshold: 0.25,
    scenarioPool: HARD_POOL,
    inventorySkew: 0.3,
  },
  {
    id: "jane-street",
    name: "Jane Street Level",
    tier: "firm",
    description: "Razor-thin tolerance, aggressive AI, classic puzzle-style dice markets.",
    fairTolerance: 0.25,
    minSpread: 1,
    maxSpread: 2,
    roundSeconds: 20,
    roundsToClear: 6,
    pnlTarget: 4,
    aiAggression: 0.85,
    aiEdgeThreshold: 0.2,
    scenarioPool: HARD_POOL,
    inventorySkew: 0.35,
  },
  {
    id: "citadel",
    name: "Citadel Level",
    tier: "firm",
    description: "Speed and precision — card and conditional dice under time pressure.",
    fairTolerance: 0.2,
    minSpread: 1,
    maxSpread: 1.75,
    roundSeconds: 18,
    roundsToClear: 7,
    pnlTarget: 5,
    aiAggression: 0.88,
    aiEdgeThreshold: 0.15,
    scenarioPool: HARD_POOL,
    inventorySkew: 0.4,
  },
  {
    id: "susquehanna",
    name: "Susquehanna Level",
    tier: "firm",
    description: "Inventory management under fire — skew your quotes or bleed P&L.",
    fairTolerance: 0.18,
    minSpread: 0.75,
    maxSpread: 1.5,
    roundSeconds: 15,
    roundsToClear: 7,
    pnlTarget: 6,
    aiAggression: 0.9,
    aiEdgeThreshold: 0.12,
    scenarioPool: HARD_POOL,
    inventorySkew: 0.5,
  },
  {
    id: "optiver",
    name: "Optiver Level",
    tier: "firm",
    description: "The gauntlet: fastest clock, tightest spreads, sharpest AI.",
    fairTolerance: 0.15,
    minSpread: 0.75,
    maxSpread: 1.25,
    roundSeconds: 12,
    roundsToClear: 8,
    pnlTarget: 8,
    aiAggression: 0.95,
    aiEdgeThreshold: 0.08,
    scenarioPool: HARD_POOL,
    inventorySkew: 0.55,
  },
];

export function getLevel(id: string): LevelConfig | undefined {
  return LEVELS.find((l) => l.id === id);
}

export const LEARN_LEVEL: Pick<
  LevelConfig,
  "fairTolerance" | "minSpread" | "maxSpread"
> = {
  fairTolerance: 1.25,
  minSpread: 0.5,
  maxSpread: 8,
};
