import type { ResourceItem, StudyPath } from "./types";

/** Curated external resources — links only; we do not host third-party text. */
export const RESOURCES: ResourceItem[] = [
  // ── Official firm prep ──────────────────────────────────────────────
  {
    id: "js_probability_markets",
    title: "Jane Street — Probability & Markets Guide",
    summary: "Firm-published PDF on probability, EV, and market-making basics.",
    why: "Primary source for what Jane Street actually tests in quant trading interviews.",
    url: "https://www.janestreet.com/probability-markets/",
    category: "official-firm",
    tracks: ["quant", "market-making", "general"],
    kind: "official",
    tags: ["probability", "expected value", "market making", "bid ask", "fair value"],
    featured: true,
  },
  {
    id: "js_interviewing",
    title: "Jane Street — Interviewing",
    summary: "Role-specific interview guides, mock videos, and process overview.",
    why: "Explains how each desk interviews and what collaborative problem-solving looks like.",
    url: "https://www.janestreet.com/join-jane-street/interviewing/",
    category: "official-firm",
    tracks: ["quant", "market-making", "general"],
    kind: "official",
    tags: ["interview", "probability", "market making"],
    featured: true,
  },
  {
    id: "js_trading_interviews",
    title: "Jane Street — Trading Interviews",
    summary: "What a Jane Street trading interview feels like, with video examples.",
    why: "Sets expectations for live market-making games and probability dialogue.",
    url: "https://www.janestreet.com/join-jane-street/interviewing/#trading-interviews",
    category: "official-firm",
    tracks: ["market-making", "quant"],
    kind: "official",
    tags: ["trading", "market making", "interview"],
  },
  {
    id: "js_swe_interview",
    title: "Jane Street — Software Engineering Interview Prep",
    summary: "How SWE interviews differ from quant — multi-part coding, not probability.",
    why: "Useful if you are targeting hybrid QR/SWE tracks; avoids preparing for the wrong format.",
    url: "https://www.janestreet.com/join-jane-street/interviewing/#software-engineering",
    category: "official-firm",
    tracks: ["general"],
    kind: "official",
    tags: ["coding", "interview"],
  },
  {
    id: "citadel_qr_process",
    title: "Citadel Securities — Quant Research Interview Process",
    summary: "Official walkthrough of QR recruiting and what researchers evaluate.",
    why: "Clarifies Citadel’s collaborative, research-heavy interview culture.",
    url: "https://www.citadelsecurities.com/careers/career-perspectives/our-quantitative-research-interview-process/",
    category: "official-firm",
    tracks: ["quant", "general"],
    kind: "official",
    tags: ["interview", "quant research"],
  },
  {
    id: "citadel_trading_faq",
    title: "Citadel — Markets & Trading Candidate FAQs",
    summary: "Official FAQ for trading and markets roles.",
    why: "Good for understanding desk structure and what “markets” means at Citadel.",
    url: "https://www.citadelsecurities.com/careers/candidate-faqs-markets-trading/",
    category: "official-firm",
    tracks: ["market-making", "quant"],
    kind: "official",
    tags: ["trading", "interview"],
  },
  {
    id: "sig_careers",
    title: "Susquehanna (SIG) — Careers & Interview Prep",
    summary: "SIG’s public hiring pages and quant game-style assessment info.",
    why: "SIG is known for probability-heavy games; start from their official materials.",
    url: "https://careers.sig.com/",
    category: "official-firm",
    tracks: ["quant", "market-making", "general"],
    kind: "official",
    tags: ["interview", "probability", "games"],
  },
  {
    id: "optiver_careers",
    title: "Optiver — Careers",
    summary: "Official Optiver recruiting and role descriptions.",
    why: "Optiver interviews emphasize mental math and short probability puzzles.",
    url: "https://www.optiver.com/working-at-optiver/career-opportunities/",
    category: "official-firm",
    tracks: ["quant", "market-making"],
    kind: "official",
    tags: ["mental math", "interview"],
  },

  // ── Probability & quant math ────────────────────────────────────────
  {
    id: "stat110_site",
    title: "Harvard Stat 110 — Probability (course site)",
    summary: "Joe Blitzstein’s full probability course: syllabus, homework, resources.",
    why: "Gold-standard free probability foundation for quant interviews.",
    url: "https://stat110.hsites.harvard.edu/",
    category: "quant-probability",
    tracks: ["quant", "general"],
    kind: "course",
    tags: ["probability", "bayes", "conditional probability", "combinatorics", "expected value"],
    featured: true,
  },
  {
    id: "stat110_youtube",
    title: "Stat 110 — YouTube Lecture Playlist",
    summary: "Full video lectures (~34 hours) covering the Stat 110 curriculum.",
    why: "Watch alongside our lessons when you want deeper theory on a topic.",
    url: "https://www.youtube.com/playlist?list=PL2SOU6wwxB0uwwH80KTQ6ht66KWxbzTIo",
    category: "quant-probability",
    tracks: ["quant", "general"],
    kind: "free",
    tags: ["probability", "bayes", "distributions", "markov"],
  },
  {
    id: "probabilitybook_net",
    title: "Introduction to Probability (Blitzstein & Hwang) — free digital edition",
    summary: "Official free web edition of the Stat 110 textbook from the authors.",
    why: "Legitimate free textbook — use this instead of leaked PDFs.",
    url: "https://probabilitybook.net/",
    category: "quant-probability",
    tracks: ["quant", "general"],
    kind: "free",
    author: "Blitzstein & Hwang",
    tags: ["probability", "statistics", "combinatorics"],
    featured: true,
  },
  {
    id: "edx_stat110",
    title: "edX — Introduction to Probability (Stat110x)",
    summary: "Interactive edX version with animations and structured problem sets.",
    why: "Structured alternative to raw YouTube if you prefer guided pacing.",
    url: "https://www.edx.org/learn/probability/harvard-university-introduction-to-probability",
    category: "courses",
    tracks: ["quant", "general"],
    kind: "course",
    tags: ["probability", "expected value"],
  },
  {
    id: "brainstellar",
    title: "Brainstellar — Quant Interview Puzzles",
    summary: "Free probability and brain-teaser puzzles with stepwise solutions.",
    why: "Excellent drill bank after our lessons — sorted by difficulty and topic.",
    url: "https://brainstellar.com/puzzles/probability/",
    category: "practice",
    tracks: ["quant", "general"],
    kind: "practice",
    tags: ["probability", "brainteaser", "expected value", "combinatorics"],
    featured: true,
  },
  {
    id: "project_euler",
    title: "Project Euler",
    summary: "Mathematical/computational puzzles that build number sense.",
    why: "Strengthens the “quick insight” muscle for harder quant puzzles.",
    url: "https://projecteuler.net/",
    category: "practice",
    tracks: ["quant", "general"],
    kind: "practice",
    tags: ["combinatorics", "number theory"],
  },
  {
    id: "aops_wiki",
    title: "Art of Problem Solving — Wiki",
    summary: "Free reference for combinatorics, probability, and contest math.",
    why: "Fast lookup when you forget a counting identity or distribution fact.",
    url: "https://artofproblemsolving.com/wiki/index.php/Main_Page",
    category: "quant-probability",
    tracks: ["quant", "general"],
    kind: "free",
    tags: ["combinatorics", "probability"],
  },
  {
    id: "mit_ocw_prob",
    title: "MIT OCW — Introduction to Probability and Statistics",
    summary: "MIT OpenCourseWare lectures and notes on probability.",
    why: "Alternative rigor if Stat 110 pacing doesn’t match your style.",
    url: "https://ocw.mit.edu/courses/18-05-introduction-to-probability-and-statistics-spring-2014/",
    category: "courses",
    tracks: ["quant", "general"],
    kind: "course",
    tags: ["probability", "statistics"],
  },

  // ── Market making ───────────────────────────────────────────────────
  {
    id: "js_blog_mm",
    title: "Jane Street Blog — Markets & Trading",
    summary: "Essays on how market makers think about risk, pricing, and games.",
    why: "Builds intuition beyond formulas — how firms talk about uncertainty.",
    url: "https://blog.janestreet.com/",
    category: "market-making",
    tracks: ["market-making", "quant"],
    kind: "article",
    tags: ["market making", "fair value", "spread", "inventory", "bid ask"],
  },
  {
    id: "harris_trading_exchanges",
    title: "Trading and Exchanges (Larry Harris)",
    summary: "Standard reference on market microstructure — order books, spreads, liquidity.",
    why: "Citadel and other firms cite this for trading-desk depth; buy from publisher.",
    url: "https://global.oup.com/academic/product/trading-and-exchanges-9780195144703",
    category: "books",
    tracks: ["market-making"],
    kind: "book",
    author: "Larry Harris",
    tags: ["market making", "spread", "liquidity", "bid ask"],
    featured: true,
  },
  {
    id: "tradermath",
    title: "TraderMath — Mental Math Drills",
    summary: "Timed arithmetic drills used by trading interview prep communities.",
    why: "Pairs with our Mental Math mode for extra reps before OA-style screens.",
    url: "https://tradermath.org/",
    category: "practice",
    tracks: ["market-making", "quant", "general"],
    kind: "practice",
    tags: ["mental math", "speed"],
  },
  {
    id: "zetamac",
    title: "Zetamac — Arithmetic Game",
    summary: "Classic timed mental-math game (add/sub/mul/div).",
    why: "Industry-standard warm-up for Jane Street / Optiver-style speed tests.",
    url: "https://arithmetic.zetamac.com/",
    category: "practice",
    tracks: ["market-making", "quant", "general"],
    kind: "practice",
    tags: ["mental math"],
  },

  // ── Poker theory ────────────────────────────────────────────────────
  {
    id: "upswing_gto",
    title: "Upswing Poker — What is GTO?",
    summary: "Accessible intro to game-theory-optimal poker and modern strategy.",
    why: "Free article explaining GTO vocabulary used in poker theory interviews.",
    url: "https://upswingpoker.com/glossary/gto/",
    category: "poker-theory",
    tracks: ["poker-theory"],
    kind: "free",
    tags: ["GTO", "game theory", "ranges", "bluffing"],
    featured: true,
  },
  {
    id: "upswing_theory_exploit",
    title: "Upswing Poker — GTO vs Exploitative Play",
    summary: "How theory and exploitation combine in modern hold’em.",
    why: "Mirrors our poker theory track: math first, then adjusting to opponents.",
    url: "https://upswingpoker.com/combine-theory-and-exploit/",
    category: "poker-theory",
    tracks: ["poker-theory"],
    kind: "free",
    tags: ["GTO", "exploitative", "ranges"],
  },
  {
    id: "upswing_preflop",
    title: "Upswing Poker — Preflop Strategy Hub",
    summary: "Free articles, quizzes, and videos on preflop decision-making.",
    why: "Solid free depth on position, 3-bets, and range thinking.",
    url: "https://upswingpoker.com/learn-preflop-poker/",
    category: "poker-theory",
    tracks: ["poker-theory"],
    kind: "free",
    tags: ["preflop", "position", "ranges"],
  },
  {
    id: "pokerstars_learn",
    title: "PokerStars Learn — Poker School",
    summary: "Beginner-to-intermediate lessons on rules, hand rankings, and basics.",
    why: "Quick refresh on fundamentals before our poker theory lessons.",
    url: "https://www.pokerstars.com/poker/learn/",
    category: "poker-theory",
    tracks: ["poker-theory", "general"],
    kind: "free",
    tags: ["fundamentals", "hand rankings", "rules"],
  },
  {
    id: "twoplustwo_forum",
    title: "Two Plus Two — Poker Theory Forum",
    summary: "Long-running community discussions on hand analysis and theory.",
    why: "Read how strong players talk through spots — good for interview narration practice.",
    url: "https://forumserver.twoplustwo.com/",
    category: "poker-theory",
    tracks: ["poker-theory"],
    kind: "article",
    tags: ["hand reading", "pot odds", "ranges"],
  },
  {
    id: "texas_solver",
    title: "TexasSolver — Open-Source GTO Solver",
    summary: "Free open-source postflop solver for equilibrium study.",
    why: "Hands-on GTO exploration without a paid subscription.",
    url: "https://github.com/bupticybee/TexasSolver",
    category: "poker-theory",
    tracks: ["poker-theory"],
    kind: "free",
    tags: ["GTO", "solver", "postflop"],
  },
  {
    id: "gtogecko_free",
    title: "GTO Gecko — Free GTO Resource Guide",
    summary: "Curated list of genuinely free GTO study tools and ranges.",
    why: "Meta-guide to free poker theory tools — complements paid solvers.",
    url: "https://gtogecko.com/blog/free-gto-resources",
    category: "meta-guides",
    tracks: ["poker-theory"],
    kind: "article",
    tags: ["GTO", "ranges", "solver"],
  },

  // ── Books (purchase — support authors) ──────────────────────────────
  {
    id: "green_book",
    title: "A Practical Guide to Quantitative Finance Interviews (“Green Book”)",
    summary: "Classic probability + brain-teaser collection for quant interviews.",
    why: "Industry standard — buy the official edition; do not use leaked PDFs.",
    url: "https://www.amazon.com/Practical-Guide-Quantitative-Finance-Interviews/dp/0979757620",
    category: "books",
    tracks: ["quant", "general"],
    kind: "book",
    author: "Xinfeng Zhou",
    tags: ["probability", "brainteaser", "expected value"],
    featured: true,
  },
  {
    id: "heard_on_street",
    title: "Heard on the Street — Quantitative Questions",
    summary: "Brain teasers and quant questions from Wall Street interviews.",
    why: "Complements the Green Book with different puzzle styles.",
    url: "https://www.amazon.com/Heard-Street-Quantitative-Questions-Finance/dp/0975974420",
    category: "books",
    tracks: ["quant", "general"],
    kind: "book",
    author: "Timothy Crack",
    tags: ["brainteaser", "probability"],
  },
  {
    id: "mosteller_50",
    title: "Fifty Challenging Problems in Probability",
    summary: "Short, classic probability puzzles with solutions.",
    why: "Great for building intuition — many ideas appear in interview variants.",
    url: "https://www.amazon.com/Fifty-Challenging-Problems-Probability-Mathematical/dp/0486653552",
    category: "books",
    tracks: ["quant", "general"],
    kind: "book",
    author: "Frederick Mosteller",
    tags: ["probability", "brainteaser"],
  },
  {
    id: "ross_probability",
    title: "A First Course in Probability (Sheldon Ross)",
    summary: "Standard undergraduate probability textbook.",
    why: "Citadel-style prep often starts here for rigorous foundations.",
    url: "https://www.pearson.com/en-us/subject-catalog/p/a-first-course-in-probability/P200000003380",
    category: "books",
    tracks: ["quant", "general"],
    kind: "book",
    author: "Sheldon Ross",
    tags: ["probability", "distributions"],
  },
  {
    id: "joshi_quant",
    title: "Quant Job Interview Questions and Answers (Mark Joshi)",
    summary: "Derivatives, stochastic calc, and quant finance interview Q&A.",
    why: "For QR roles that go beyond pure probability into pricing.",
    url: "https://www.amazon.com/Quant-Job-Interview-Questions-Answers/dp/0995451727",
    category: "books",
    tracks: ["quant"],
    kind: "book",
    author: "Mark Joshi",
    tags: ["derivatives", "stochastic calculus"],
  },
  {
    id: "math_of_poker",
    title: "The Mathematics of Poker (Bill Chen & Jerrod Ankenman)",
    summary: "Quantitative treatment of poker decision-making and game theory.",
    why: "Bridges our poker theory track with formal game-theory language.",
    url: "https://www.amazon.com/Mathematics-Poker-Bill-Chen/dp/1886070253",
    category: "books",
    tracks: ["poker-theory", "quant"],
    kind: "book",
    author: "Chen & Ankenman",
    tags: ["game theory", "pot odds", "GTO"],
  },
  {
    id: "applications_nlh",
    title: "Applications of No-Limit Hold’em (Matthew Janda)",
    summary: "Theory-backed exploitative framework for NLHE.",
    why: "Connects solver-era GTO ideas to practical table decisions.",
    url: "https://www.amazon.com/Applications-No-Limit-Hold-em-Matthew-Janda/dp/0983959750",
    category: "books",
    tracks: ["poker-theory"],
    kind: "book",
    author: "Matthew Janda",
    tags: ["GTO", "ranges", "postflop"],
  },

  // ── Practice platforms ────────────────────────────────────────────────
  {
    id: "quantguide",
    title: "QuantGuide",
    summary: "Large bank of quant interview questions with solutions.",
    why: "Popular paid prep platform — use after mastering our lesson foundations.",
    url: "https://www.quantguide.io/",
    category: "practice",
    tracks: ["quant", "market-making", "general"],
    kind: "practice",
    tags: ["probability", "brainteaser", "interview"],
  },
  {
    id: "quantquestions",
    title: "QuantQuestions.io",
    summary: "Interview question database for trading and quant roles.",
    why: "Extra reps on firm-style questions once you can explain our lesson solutions.",
    url: "https://www.quantquestions.io/",
    category: "practice",
    tracks: ["quant", "market-making"],
    kind: "practice",
    tags: ["interview", "probability"],
  },
  {
    id: "leetcode",
    title: "LeetCode",
    summary: "Coding interview practice (arrays, DP, graphs).",
    why: "Required for hybrid QR/SWE tracks — not the focus of pure trading interviews.",
    url: "https://leetcode.com/",
    category: "practice",
    tracks: ["general"],
    kind: "practice",
    tags: ["coding", "algorithms"],
  },

  // ── Meta-guides (lists of resources) ────────────────────────────────
  {
    id: "quantt_citadel",
    title: "Quantt — Citadel Interview Guide",
    summary: "Third-party guide with book list and prep timeline for Citadel.",
    why: "Useful meta-list — cross-check recommendations against official firm pages.",
    url: "https://www.quantt.co.uk/resources/citadel-interview",
    category: "meta-guides",
    tracks: ["quant", "general"],
    kind: "article",
    tags: ["interview", "books", "citadel"],
  },
  {
    id: "quantt_become_quant",
    title: "Quantt — How to Become a Quant",
    summary: "Educational pathways and reading lists for quant careers.",
    why: "Bird’s-eye view of what to study and in what order.",
    url: "https://www.quantt.co.uk/resources/how-to-become-a-quant",
    category: "meta-guides",
    tracks: ["quant", "general"],
    kind: "article",
    tags: ["career", "books", "probability"],
  },
  {
    id: "wilmott",
    title: "Wilmott Forums",
    summary: "Quant finance community — career threads and technical discussion.",
    why: "Long-running forum for quant career advice and interview war stories.",
    url: "https://forum.wilmott.com/",
    category: "meta-guides",
    tracks: ["quant", "general"],
    kind: "article",
    tags: ["career", "quant finance"],
  },
  {
    id: "red_chip",
    title: "Red Chip Poker — Free Strategy Articles",
    summary: "Free poker strategy content aimed at live and online players.",
    why: "Another free theory angle — pot odds, sizing, and live tells.",
    url: "https://redchippoker.com/strategy/",
    category: "poker-theory",
    tracks: ["poker-theory"],
    kind: "free",
    tags: ["pot odds", "sizing", "exploitative"],
  },
  {
    id: "splitsuit",
    title: "SplitSuit — Poker Math & Strategy",
    summary: "Free videos and articles on poker math fundamentals.",
    why: "Clear explanations of equity, pot odds, and implied odds.",
    url: "https://www.splitsuit.com/",
    category: "poker-theory",
    tracks: ["poker-theory"],
    kind: "free",
    tags: ["pot odds", "equity", "fundamentals"],
  },
];

export const STUDY_PATHS: StudyPath[] = [
  {
    id: "quant_foundation",
    track: "quant",
    title: "Quant probability foundation",
    description:
      "Start with official free probability, drill puzzles, then buy interview books.",
    steps: [
      {
        label: "1. Core probability (free)",
        resourceIds: ["stat110_site", "probabilitybook_net", "stat110_youtube"],
      },
      {
        label: "2. Interview-style drills",
        resourceIds: ["brainstellar", "js_probability_markets"],
      },
      {
        label: "3. Deepen with books",
        resourceIds: ["green_book", "mosteller_50", "ross_probability"],
      },
      {
        label: "4. Firm-specific prep",
        resourceIds: ["js_interviewing", "citadel_qr_process", "sig_careers"],
      },
    ],
  },
  {
    id: "mm_foundation",
    track: "market-making",
    title: "Market making interview path",
    description:
      "Jane Street’s guide first, then microstructure reading and speed drills.",
    steps: [
      {
        label: "1. Official market-making intro",
        resourceIds: ["js_probability_markets", "js_trading_interviews"],
      },
      {
        label: "2. Practice in-app + speed",
        resourceIds: ["tradermath", "zetamac"],
      },
      {
        label: "3. Microstructure depth",
        resourceIds: ["harris_trading_exchanges", "js_blog_mm"],
      },
    ],
  },
  {
    id: "poker_foundation",
    track: "poker-theory",
    title: "Poker theory for quant interviews",
    description:
      "Pot odds and GTO basics free online, then theory books for depth.",
    steps: [
      {
        label: "1. Free theory articles",
        resourceIds: ["upswing_gto", "upswing_preflop", "splitsuit"],
      },
      {
        label: "2. Solver-era tools",
        resourceIds: ["texas_solver", "gtogecko_free"],
      },
      {
        label: "3. Books",
        resourceIds: ["math_of_poker", "applications_nlh"],
      },
    ],
  },
];
